name: rnaseq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cutadapt=2.9
  - fastqc=0.11.9
  - pandas=1.0.3
  - samtools=1.10
  - star=2.7.3a
  - stringtie=2.1.1
  - trim-galore=0.6.5
