name: tagada
dependencies:
  - bioconda::bedtools=2.29.2
  - bioconda::bioconductor-edger=3.30.0
  - bioconda::bioconductor-gostats=2.54.0
  - bioconda::bioconductor-hgu95av2.db=3.2.3
  - bioconda::cutadapt=3.3
  - bioconda::fastqc=0.11.9
  - bioconda::feelnc=0.2
  - bioconda::multiqc=1.12
  - bioconda::samtools=1.10
  - bioconda::star=2.7.10a
  - bioconda::stringtie=2.1.7
  - bioconda::subread=2.0.1
  - bioconda::trim-galore=0.6.5
  - conda-forge::gawk=5.1.0
  - conda-forge::imagemagick=7.0.10_28
  - conda-forge::pandas=1.3.3
  - conda-forge::r-ggdendro=0.1-20
  - conda-forge::r-ggplot2=3.3.2
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-plyr=1.8.6
  - conda-forge::r-reshape2=1.4.4
