name: rnaseq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bedtools=2.29.2
  - bioconductor-edger=3.30.0
  - bioconductor-gostats=2.54.0
  - bioconductor-hgu95av2.db=3.2.3
  - cutadapt=2.10
  - fastqc=0.11.9
  - multiqc=1.9
  - pandas=1.0.3
  - r-ggdendro=0.1-20
  - r-ggplot2=3.3.2
  - r-optparse=1.6.6
  - r-plyr=1.8.6
  - r-reshape2=1.4.4
  - samtools=1.10
  - star=2.7.3a
  - stringtie=2.1.1
  - subread=1.6.0
  - trim-galore=0.6.5
