#!/bin/bash

# Parse arguments
command=("$0")
escape="'\''"
command+=("'${1//\'/$escape}'")
[[ -f "$1" || -d "$1" ]] && pipeline=$(readlink -m "$1") || pipeline="$1"
shift
while (( "$#" )); do
  # Split --option=parameter into two variables
  [[ "$1" == --*=* ]] && set -- "${1%%=*}" "${1#*=}" "${@:2}"
  case "$1" in
    # Parse output directory
    --output|--outdir)
      command+=("$1")
      if [[ -n "$2" && "$2" != -* ]]; then
        command+=("'${2//\'/$escape}'")
        output=$(readlink -m "$2")
        shift
      fi
      shift
      ;;
    # Parse work directory
    --workdir|--work-dir|-work-dir|-w)
      command+=("$1")
      if [[ -n "$2" && "$2" != -* ]]; then
        command+=("'${2//\'/$escape}'")
        workdir=$(readlink -m "$2")
        shift
      fi
      shift
      ;;
    # Parse resume option
    --resume|-resume)
      command+=("$1")
      args+=("-resume")
      resume=true
      shift
      ;;
    # Parse overridden nextflow options
    --with-report|-with-report|--with-timeline|-with-timeline)
      command+=("$1")
      if [[ -n "$2" && "$2" != -* ]]; then
        command+=("'${2//\'/$escape}'")
        shift
      fi
      shift
      ;;
    # Parse nextflow options passed as pipeline options
    --ansi-log|--bucket-dir|--cache|--config|--dump-channels|--dump-hashes|--e.?*|--entry|--help|--hub|--latest|--lib|--name|--offline|--params-file|--process.?*|--profile|--qs|--queue-size|--revision|--test|--user|--with-conda|--with-dag|--with-docker|--with-notification|--with-podman|--with-singularity|--with-tower|--with-trace|--with-weblog|--without-docker|--without-podman)
      command+=("$1")
      args+=("${1#-}")
      shift
      ;;
    # Parse options
    -?*)
      command+=("$1")
      args+=("$1")
      shift
      ;;
    # Parse other arguments
    *)
      command+=("'${1//\'/$escape}'")
      args+=("$1")
      shift
      ;;
  esac
done

# Check required arguments
if [[ -z "$pipeline" || -z "$output" ]]; then
  echo "Usage: $0 <pipeline> --output <directory> [arguments]"
  exit 1
fi

if [[ -z "$workdir" ]]; then
  workdir="$output"
fi

# Prepare nextflow temp folder
mkdir -p "$output" "$workdir"/temp
ln -sf "$workdir"/temp "$output"/.nextflow
rm -rf "$workdir"/temp/input
rm -rf "$output"/logs/nextflow.log
rm -rf "$output"/logs/report.html
rm -rf "$output"/logs/timeline.html

# Write command to history
mkdir -p "$output"/logs
[ -f "$output"/logs/command.log ] && echo "" >> "$output"/logs/command.log
echo $(date '+%Y/%m/%d %H:%M:%S')$'\t'"${command[@]}" >> "$output"/logs/command.log

# Parse arguments
set -- "${args[@]}"
args=()
while (( "$#" )); do
  case "$1" in
    # Parse options and parameters
    -?*)
      args+=("$1")
      [[ "$1" == --* ]] && glob=true || glob=false
      option="${1#--}"
      path=""
      paths=""
      values=""
      params=""
      count=0
      while [[ -n "$2" && "$2" != -* ]]; do
        count=$(( count + 1 ))
        if [[ $glob == true && (-f "$2" || -d "$2") ]]; then
          # Create symlink to original path
          path="$2"
          symlink=$(basename "$2")
          symlink="$workdir"/temp/input/"$option"/"$symlink"
          mkdir -p "$workdir"/temp/input/"$option"
          ln -sf "$2" "$symlink"
          # Replace path with glob to symlink
          paths="$workdir"/temp/input/"$option"/*
        else
          # Join values with commas
          values+="$2",
        fi
        shift
      done
      if [[ $count == 1 ]]; then
        paths="$path"
      fi
      params+="$values"
      params+="$paths"
      params="${params%,}"
      args+=("$params")
      shift
      ;;
    # Parse other arguments
    *)
      args+=("$1")
      shift
      ;;
  esac
done

# Go to output directory
cd "$output"

# Run nextflow pipeline and remove temp folder
# after pipeline successfully completes
nextflow \
-log "$output"/logs/nextflow.log \
run "$pipeline" \
-with-report "$output"/logs/report.html \
-with-timeline "$output"/logs/timeline.html \
-work-dir "$workdir"/temp/work \
--output "$output" \
--outdir "$output" \
"${args[@]}" \
&& rm -rf "$output"/.nextflow \
&& if [[ -z "$resume" ]]; then rm -rf "$workdir"/temp; fi
